using System;
using System.Diagnostics;
using System.IO;
using System.Windows.Forms;

namespace StudentHubSetup
{
    static class Program
    {
        // Embedded standalone launcher binary base64
        private const string EmbeddedLauncherBase64 = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAIp7rWoAAAAAAAAAAOAAAgELAQsAAAgAAAAIAAAAAAAAricAAAAgAAAAQAAAAABAAAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAIAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAFgnAABTAAAAAEAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAAtAcAAAAgAAAACAAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAAAFAAAAQAAAAAYAAAAKAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAAEAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAACQJwAAAAAAAEgAAAACAAUAOCEAACAGAAABAAAAAQAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABswBADMAAAAAQAAEXIBAABwCnJbAABwBigEAAAKCx8qKAUAAApyoQAAcCgGAAAKDAgoBwAACi0SHyYoBQAACnKhAABwKAYAAAoMCCgHAAAKLAoIBygIAAAKJt57HyYoBQAACnLtAABwKAYAAAoNCSgHAAAKLRIfKigFAAAKcu0AAHAoBgAACg0JKAcAAAosCgkHKAgAAAom3j0GcwkAAAoTBBEEF28KAAAKEQQoCwAACibeIxMFcjcBAHARBW8MAAAKKA0AAApydQEAcBYfECgOAAAKJt4AKgEQAAAAAAAAqKgAIwwAAAFCU0pCAQABAAAAAAAMAAAAdjQuMC4zMDMxOQAAAAAFAGwAAACMAQAAI34AAPgBAADoAQAAI1N0cmluZ3MAAAAA4AMAAKABAAAjVVMAgAUAABAAAAAjR1VJRAAAAJAFAACQAAAAI0Jsb2IAAAAAAAAAAgAAAUcUAgAJAAAAAPolMwAWAAABAAAAEAAAAAIAAAABAAAADgAAAAMAAAABAAAAAQAAAAMAAAAAAAoAAQAAAAAABgBDADwABgBvAE8ABgCVAE8ABgDFADwABgDYADwABgDmADwAGwDyAAAABgAYAQ4BBgAlAQ4BCgBEATEBCgBSATEBBgB3ATwADgCpAZQBDgC0AZQBDgDBAZQBDgDTAZQBAAAAAAEAAAAAAAEAAQCAARAAIAAoAAUAAQABAFAgAAAAAJEASgAKAAEAEQCPAA4AGQCPABMAIQCPABMAKQDfABwAMQAAASIAQQAdASgASQAqAS4AUQBMATMAWQCPADoAWQBjAT8AUQBMAUQAYQCBAUsAKQCNASgAaQDiAU8AIAAbABcALgALAGUALgATAG4AWgAEgAAAAAAAAAAAAAAAAAAAAACzAAAABAAAAAAAAAAAAAAAAQAzAAAAAAAEAAAAAAAAAAAAAAABADwAAAAAAAQAAAAAAAAAAAAAAAEAlAEAAAAAAAAAPE1vZHVsZT4AU3R1ZGVudC1IdWItQWRtaW4uZXhlAFByb2dyYW0AU3R1ZGVudEh1YgBtc2NvcmxpYgBTeXN0ZW0AT2JqZWN0AE1haW4AU3lzdGVtLlJ1bnRpbWUuQ29tcGlsZXJTZXJ2aWNlcwBDb21waWxhdGlvblJlbGF4YXRpb25zQXR0cmlidXRlAC5jdG9yAFJ1bnRpbWVDb21wYXRpYmlsaXR5QXR0cmlidXRlAFN0dWRlbnQtSHViLUFkbWluAFNUQVRocmVhZEF0dHJpYnV0ZQBTdHJpbmcARm9ybWF0AEVudmlyb25tZW50AFNwZWNpYWxGb2xkZXIAR2V0Rm9sZGVyUGF0aABTeXN0ZW0uSU8AUGF0aABDb21iaW5lAEZpbGUARXhpc3RzAFN5c3RlbS5EaWFnbm9zdGljcwBQcm9jZXNzAFN0YXJ0AFByb2Nlc3NTdGFydEluZm8Ac2V0X1VzZVNoZWxsRXhlY3V0ZQBFeGNlcHRpb24AZ2V0X01lc3NhZ2UAQ29uY2F0AFN5c3RlbS5XaW5kb3dzLkZvcm1zAE1lc3NhZ2VCb3gARGlhbG9nUmVzdWx0AE1lc3NhZ2VCb3hCdXR0b25zAE1lc3NhZ2VCb3hJY29uAFNob3cAAABZaAB0AHQAcABzADoALwAvAHkAZQBoAGkAYQAtAHAAcgBvAGoAZQBjAHQAcwAuAHYAZQByAGMAZQBsAC4AYQBwAHAALwBhAGQAbQBpAG4ALgBoAHQAbQBsAAFFLQAtAGEAcABwAD0AIgB7ADAAfQAiACAALQAtAHcAaQBuAGQAbwB3AC0AcwBpAHoAZQA9ADEAMwA2ADYALAA4ADUAMAABS00AaQBjAHIAbwBzAG8AZgB0AFwARQBkAGcAZQBcAEEAcABwAGwAaQBjAGEAdABpAG8AbgBcAG0AcwBlAGQAZwBlAC4AZQB4AGUAAElHAG8AbwBnAGwAZQBcAEMAaAByAG8AbQBlAFwAQQBwAHAAbABpAGMAYQB0AGkAbwBuAFwAYwBoAHIAbwBtAGUALgBlAHgAZQAAPS4GNwYjBiAAIwYrBkYGJwYhBiAAKgY0BjoGSgZEBiAARAZIBi0GKQYgACcGRAYlBi8GJwYxBikGOgAKAAEnUwB0AHUAZABlAG4AdAAgAEgAdQBiACAARABlAHMAawB0AG8AcAAAAAAAemjxYYY800ur9XSbreB21wAIt3pcVhk04IkDAAABBCABAQgDIAABBAEAAAAFAAIODhwFAAEOER0FAAIODg4EAAECDgYAAhIpDg4EIAEBDgQgAQECBgABEikSLQMgAA4KAAQROQ4OET0RQQoHBg4ODg4SLRIxCAEACAAAAAAAHgEAAQBUAhZXcmFwTm9uRXhjZXB0aW9uVGhyb3dzAQAAAIAnAAAAAAAAAAAAAJ4nAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQJwAAAAAAAAAAAAAAAAAAAABfQ29yRXhlTWFpbgBtc2NvcmVlLmRsbAAAAAAA/yUAIEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAQAAAAIAAAgBgAAAA4AACAAAAAAAAAAAAAAAAAAAABAAEAAABQAACAAAAAAAAAAAAAAAAAAAABAAEAAABoAACAAAAAAAAAAAAAAAAAAAABAAAAAACAAAAAAAAAAAAAAAAAAAAAAAABAAAAAACQAAAAoEAAAGwCAAAAAAAAAAAAABBDAADqAQAAAAAAAAAAAABsAjQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAAEAAAAAQAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBuAGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAAALAEzAEAAAEAUwB0AHIAaQBuAGcARgBpAGwAZQBJAG4AZgBvAAAAqAEAAAEAMAAwADAAMAAwADQAYgAwAAAALAACAAEARgBpAGwAZQBEAGUAcwBjAHIAaQBwAHQAaQBvAG4AAAAAACAAAAAwAAgAAQBGAGkAbABlAFYAZQByAHMAaQBvAG4AAAAAADAALgAwAC4AMAAuADAAAABMABYAAQBJAG4AdABlAHIAbgBhAGwATgBhAG0AZQAAAFMAdAB1AGQAZQBuAHQALQBIAHUAYgAtAEEAZABtAGkAbgAuAGUAeABlAAAAKAACAAEATABlAGcAYQBsAEMAbwBwAHkAcgBpAGcAaAB0AAAAIAAAAFQAFgABAE8AcgBpAGcAaQBuAGEAbABGAGkAbABlAG4AYQBtAGUAAABTAHQAdQBkAGUAbgB0AC0ASAB1AGIALQBBAGQAbQBpAG4ALgBlAHgAZQAAADQACAABAFAAcgBvAGQAdQBjAHQAVgBlAHIAcwBpAG8AbgAAADAALgAwAC4AMAAuADAAAAA4AAgAAQBBAHMAcwBlAG0AYgBsAHkAIABWAGUAcgBzAGkAbwBuAAAAMAAuADAALgAwAC4AMAAAAAAAAADvu788P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJVVEYtOCIgc3RhbmRhbG9uZT0ieWVzIj8+DQo8YXNzZW1ibHkgeG1sbnM9InVybjpzY2hlbWFzLW1pY3Jvc29mdC1jb206YXNtLnYxIiBtYW5pZmVzdFZlcnNpb249IjEuMCI+DQogIDxhc3NlbWJseUlkZW50aXR5IHZlcnNpb249IjEuMC4wLjAiIG5hbWU9Ik15QXBwbGljYXRpb24uYXBwIi8+DQogIDx0cnVzdEluZm8geG1sbnM9InVybjpzY2hlbWFzLW1pY3Jvc29mdC1jb206YXNtLnYyIj4NCiAgICA8c2VjdXJpdHk+DQogICAgICA8cmVxdWVzdGVkUHJpdmlsZWdlcyB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjMiPg0KICAgICAgICA8cmVxdWVzdGVkRXhlY3V0aW9uTGV2ZWwgbGV2ZWw9ImFzSW52b2tlciIgdWlBY2Nlc3M9ImZhbHNlIi8+DQogICAgICA8L3JlcXVlc3RlZFByaXZpbGVnZXM+DQogICAgPC9zZWN1cml0eT4NCiAgPC90cnVzdEluZm8+DQo8L2Fzc2VtYmx5Pg0KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAMAAAAsDcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

        [STAThread]
        static void Main()
        {
            try
            {
                string appDir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "StudentHub");
                if (!Directory.Exists(appDir))
                {
                    Directory.CreateDirectory(appDir);
                }

                string targetExePath = Path.Combine(appDir, "Student-Hub-Admin.exe");
                string currentDir = AppDomain.CurrentDomain.BaseDirectory;
                string sourceExe = Path.Combine(currentDir, "Student-Hub-Admin.exe");

                // If local file exists, copy it; otherwise decode from embedded payload
                if (File.Exists(sourceExe))
                {
                    File.Copy(sourceExe, targetExePath, true);
                }
                else
                {
                    byte[] binaryData = Convert.FromBase64String(EmbeddedLauncherBase64);
                    File.WriteAllBytes(targetExePath, binaryData);
                }

                // Create Desktop & Start Menu Shortcuts via PowerShell COM
                string desktopFolder = Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory);
                string startMenuFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.StartMenu), "Programs");

                string desktopLnk = Path.Combine(desktopFolder, "Student Hub - إدارة السنتر.lnk");
                string startMenuLnk = Path.Combine(startMenuFolder, "Student Hub.lnk");

                string psCmd = string.Format(
                    @"$ws = New-Object -ComObject WScript.Shell; " +
                    @"$s1 = $ws.CreateShortcut('{0}'); $s1.TargetPath = '{1}'; $s1.Description = 'نظام إدارة السنتر الذكي والتحضير السحابي'; $s1.Save(); " +
                    @"$s2 = $ws.CreateShortcut('{2}'); $s2.TargetPath = '{1}'; $s2.Description = 'نظام إدارة السنتر الذكي والتحضير السحابي'; $s2.Save();",
                    desktopLnk.Replace("'", "''"),
                    targetExePath.Replace("'", "''"),
                    startMenuLnk.Replace("'", "''")
                );

                ProcessStartInfo psi = new ProcessStartInfo("powershell.exe", "-NoProfile -ExecutionPolicy Bypass -Command \"" + psCmd + "\"")
                {
                    WindowStyle = ProcessWindowStyle.Hidden,
                    CreateNoWindow = true,
                    UseShellExecute = false
                };
                Process.Start(psi).WaitForExit();

                // Launch the installed app immediately
                if (File.Exists(targetExePath))
                {
                    Process.Start(targetExePath);
                }

                MessageBox.Show(
                    "تم تثبيت برنامج إدارة السنتر الذكي بنجاح على جهازك! ✅\n\n- تم تشغيل البرنامج الآن بنجاح.\n- تم إنشاء اختصار دائم على سطح المكتب (Desktop).\n- تم إنشاء اختصار في قائمة ابدأ (Start Menu).",
                    "Student Hub Setup",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );
            }
            catch (Exception ex)
            {
                MessageBox.Show("حدث خطأ أثناء التثبيت: " + ex.Message, "Student Hub Setup", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
    }
}
