using System;
using System.Diagnostics;
using System.IO;
using System.Windows.Forms;

namespace StudentHubSetup
{
    static class Program
    {
        // Embedded standalone launcher binary base64
        private const string EmbeddedLauncherBase64 = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAAWurWoAAAAAAAAAAOAAAgELAQsAAAgAAAAIAAAAAAAA7icAAAAgAAAAQAAAAABAAAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAIAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAJgnAABTAAAAAEAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAA9AcAAAAgAAAACAAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAAAFAAAAQAAAAAYAAAAKAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAAEAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAADQJwAAAAAAAEgAAAACAAUAYCEAADgGAAABAAAAAQAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABswBADzAAAAAQAAEQAAcgEAAHAKcnUAAHAGKAQAAAoLHyooBQAACnK7AABwKAYAAAoMCCgHAAAKEwYRBi0UAB8mKAUAAApyuwAAcCgGAAAKDAAIKAcAAAoW/gETBhEGLQ4ACAcoCAAACibdjgAAAB8mKAUAAApyBwEAcCgGAAAKDQkoBwAAChMGEQYtFAAfKigFAAAKcgcBAHAoBgAACg0ACSgHAAAKFv4BEwYRBi0LAAkHKAgAAAom3kIGcwkAAAoTBBEEF28KAAAKABEEKAsAAAomAN4lEwUAclEBAHARBW8MAAAKKA0AAApyjwEAcBYfECgOAAAKJgDeAAAAKgABEAAAAAABAMrLACUMAAABQlNKQgEAAQAAAAAADAAAAHY0LjAuMzAzMTkAAAAABQBsAAAAjAEAACN+AAD4AQAA6AEAACNTdHJpbmdzAAAAAOADAAC4AQAAI1VTAJgFAAAQAAAAI0dVSUQAAACoBQAAkAAAACNCbG9iAAAAAAAAAAIAAAFHFAIACQAAAAD6JTMAFgAAAQAAABAAAAACAAAAAQAAAA4AAAADAAAAAQAAAAEAAAADAAAAAAAKAAEAAAAAAAYAQwA8AAYAbwBPAAYAlQBPAAYAxQA8AAYA2AA8AAYA5gA8ABsA8gAAAAYAGAEOAQYAJQEOAQoARAExAQoAUgExAQYAdwE8AA4AqQGUAQ4AtAGUAQ4AwQGUAQ4A0wGUAQAAAAABAAAAAAABAAEAgAEQACAAKAAFAAEAAQBQIAAAAACRAEoACgABABEAjwAOABkAjwATACEAjwATACkA3wAcADEAAAEiAEEAHQEoAEkAKgEuAFEATAEzAFkAjwA6AFkAYwE/AFEATAFEAGEAgQFLACkAjQEoAGkA4gFPACAAGwAXAC4ACwBmAC4AEwBvAFoABIAAAAAAAAAAAAAAAAAAAAAAswAAAAQAAAAAAAAAAAAAAAEAMwAAAAAABAAAAAAAAAAAAAAAAQA8AAAAAAAEAAAAAAAAAAAAAAABAJQBAAAAAAAAADxNb2R1bGU+AFN0dWRlbnQtSHViLUFkbWluLmV4ZQBQcm9ncmFtAFN0dWRlbnRIdWIAbXNjb3JsaWIAU3lzdGVtAE9iamVjdABNYWluAFN5c3RlbS5SdW50aW1lLkNvbXBpbGVyU2VydmljZXMAQ29tcGlsYXRpb25SZWxheGF0aW9uc0F0dHJpYnV0ZQAuY3RvcgBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBTdHVkZW50LUh1Yi1BZG1pbgBTVEFUaHJlYWRBdHRyaWJ1dGUAU3RyaW5nAEZvcm1hdABFbnZpcm9ubWVudABTcGVjaWFsRm9sZGVyAEdldEZvbGRlclBhdGgAU3lzdGVtLklPAFBhdGgAQ29tYmluZQBGaWxlAEV4aXN0cwBTeXN0ZW0uRGlhZ25vc3RpY3MAUHJvY2VzcwBTdGFydABQcm9jZXNzU3RhcnRJbmZvAHNldF9Vc2VTaGVsbEV4ZWN1dGUARXhjZXB0aW9uAGdldF9NZXNzYWdlAENvbmNhdABTeXN0ZW0uV2luZG93cy5Gb3JtcwBNZXNzYWdlQm94AERpYWxvZ1Jlc3VsdABNZXNzYWdlQm94QnV0dG9ucwBNZXNzYWdlQm94SWNvbgBTaG93AAAAc2gAdAB0AHAAcwA6AC8ALwB5AGUAaABpAGEALQBwAHIAbwBqAGUAYwB0AHMALgB2AGUAcgBjAGUAbAAuAGEAcABwAC8AYQBkAG0AaQBuAD8AdgA9ADMALgAwAC4AMgAmAGQAZQBzAGsAdABvAHAAPQAxAAFFLQAtAGEAcABwAD0AIgB7ADAAfQAiACAALQAtAHcAaQBuAGQAbwB3AC0AcwBpAHoAZQA9ADEAMwA2ADYALAA4ADUAMAABS00AaQBjAHIAbwBzAG8AZgB0AFwARQBkAGcAZQBcAEEAcABwAGwAaQBjAGEAdABpAG8AbgBcAG0AcwBlAGQAZwBlAC4AZQB4AGUAAElHAG8AbwBnAGwAZQBcAEMAaAByAG8AbQBlAFwAQQBwAHAAbABpAGMAYQB0AGkAbwBuAFwAYwBoAHIAbwBtAGUALgBlAHgAZQAAPS4GNwYjBiAAIwYrBkYGJwYhBiAAKgY0BjoGSgZEBiAARAZIBi0GKQYgACcGRAYlBi8GJwYxBikGOgAKAAEnUwB0AHUAZABlAG4AdAAgAEgAdQBiACAARABlAHMAawB0AG8AcAAAAExhBjY1sXFNoH9nydmLnTgACLd6XFYZNOCJAwAAAQQgAQEIAyAAAQQBAAAABQACDg4cBQABDhEdBQACDg4OBAABAg4GAAISKQ4OBCABAQ4EIAEBAgYAARIpEi0DIAAOCgAEETkODhE9EUELBwcODg4OEi0SMQIIAQAIAAAAAAAeAQABAFQCFldyYXBOb25FeGNlcHRpb25UaHJvd3MBAADAJwAAAAAAAAAAAADeJwAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0CcAAAAAAAAAAAAAAAAAAAAAX0NvckV4ZU1haW4AbXNjb3JlZS5kbGwAAAAAAP8lACBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAQAAAAIAAAgBgAAAA4AACAAAAAAAAAAAAAAAAAAAABAAEAAABQAACAAAAAAAAAAAAAAAAAAAABAAEAAABoAACAAAAAAAAAAAAAAAAAAAABAAAAAACAAAAAAAAAAAAAAAAAAAAAAAABAAAAAACQAAAAoEAAAGwCAAAAAAAAAAAAABBDAADqAQAAAAAAAAAAAABsAjQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAAEAAAAAQAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBuAGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAAALAEzAEAAAEAUwB0AHIAaQBuAGcARgBpAGwAZQBJAG4AZgBvAAAAqAEAAAEAMAAwADAAMAAwADQAYgAwAAAALAACAAEARgBpAGwAZQBEAGUAcwBjAHIAaQBwAHQAaQBvAG4AAAAAACAAAAAwAAgAAQBGAGkAbABlAFYAZQByAHMAaQBvAG4AAAAAADAALgAwAC4AMAAuADAAAABMABYAAQBJAG4AdABlAHIAbgBhAGwATgBhAG0AZQAAAFMAdAB1AGQAZQBuAHQALQBIAHUAYgAtAEEAZABtAGkAbgAuAGUAeABlAAAAKAACAAEATABlAGcAYQBsAEMAbwBwAHkAcgBpAGcAaAB0AAAAIAAAAFQAFgABAE8AcgBpAGcAaQBuAGEAbABGAGkAbABlAG4AYQBtAGUAAABTAHQAdQBkAGUAbgB0AC0ASAB1AGIALQBBAGQAbQBpAG4ALgBlAHgAZQAAADQACAABAFAAcgBvAGQAdQBjAHQAVgBlAHIAcwBpAG8AbgAAADAALgAwAC4AMAAuADAAAAA4AAgAAQBBAHMAcwBlAG0AYgBsAHkAIABWAGUAcgBzAGkAbwBuAAAAMAAuADAALgAwAC4AMAAAAAAAAADvu788P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJVVEYtOCIgc3RhbmRhbG9uZT0ieWVzIj8+DQo8YXNzZW1ibHkgeG1sbnM9InVybjpzY2hlbWFzLW1pY3Jvc29mdC1jb206YXNtLnYxIiBtYW5pZmVzdFZlcnNpb249IjEuMCI+DQogIDxhc3NlbWJseUlkZW50aXR5IHZlcnNpb249IjEuMC4wLjAiIG5hbWU9Ik15QXBwbGljYXRpb24uYXBwIi8+DQogIDx0cnVzdEluZm8geG1sbnM9InVybjpzY2hlbWFzLW1pY3Jvc29mdC1jb206YXNtLnYyIj4NCiAgICA8c2VjdXJpdHk+DQogICAgICA8cmVxdWVzdGVkUHJpdmlsZWdlcyB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjMiPg0KICAgICAgICA8cmVxdWVzdGVkRXhlY3V0aW9uTGV2ZWwgbGV2ZWw9ImFzSW52b2tlciIgdWlBY2Nlc3M9ImZhbHNlIi8+DQogICAgICA8L3JlcXVlc3RlZFByaXZpbGVnZXM+DQogICAgPC9zZWN1cml0eT4NCiAgPC90cnVzdEluZm8+DQo8L2Fzc2VtYmx5Pg0KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAMAAAA8DcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

        [STAThread]
        static void Main()
        {
            try
            {
                string appDir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "StudentHub");
                if (!Directory.Exists(appDir))
                {
                    Directory.CreateDirectory(appDir);
                }

                string targetExePath = Path.Combine(appDir, "Student-Hub-Admin.exe");
                string currentDir = AppDomain.CurrentDomain.BaseDirectory;
                string sourceExe = Path.Combine(currentDir, "Student-Hub-Admin.exe");

                // If local file exists, copy it; otherwise decode from embedded payload
                if (File.Exists(sourceExe))
                {
                    File.Copy(sourceExe, targetExePath, true);
                }
                else
                {
                    byte[] binaryData = Convert.FromBase64String(EmbeddedLauncherBase64);
                    File.WriteAllBytes(targetExePath, binaryData);
                }

                // Create Desktop & Start Menu Shortcuts via PowerShell COM
                string desktopFolder = Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory);
                string startMenuFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.StartMenu), "Programs");

                string desktopLnk = Path.Combine(desktopFolder, "Student Hub - إدارة السنتر.lnk");
                string startMenuLnk = Path.Combine(startMenuFolder, "Student Hub.lnk");

                string psCmd = string.Format(
                    @"$ws = New-Object -ComObject WScript.Shell; " +
                    @"$s1 = $ws.CreateShortcut('{0}'); $s1.TargetPath = '{1}'; $s1.Description = 'نظام إدارة السنتر الذكي والتحضير السحابي'; $s1.Save(); " +
                    @"$s2 = $ws.CreateShortcut('{2}'); $s2.TargetPath = '{1}'; $s2.Description = 'نظام إدارة السنتر الذكي والتحضير السحابي'; $s2.Save();",
                    desktopLnk.Replace("'", "''"),
                    targetExePath.Replace("'", "''"),
                    startMenuLnk.Replace("'", "''")
                );

                ProcessStartInfo psi = new ProcessStartInfo("powershell.exe", "-NoProfile -ExecutionPolicy Bypass -Command \"" + psCmd + "\"")
                {
                    WindowStyle = ProcessWindowStyle.Hidden,
                    CreateNoWindow = true,
                    UseShellExecute = false
                };
                Process.Start(psi).WaitForExit();

                // Launch the installed app immediately
                if (File.Exists(targetExePath))
                {
                    Process.Start(targetExePath);
                }

                MessageBox.Show(
                    "تم تثبيت برنامج إدارة السنتر الذكي بنجاح على جهازك! ✅\n\n- تم تشغيل البرنامج الآن بنجاح.\n- تم إنشاء اختصار دائم على سطح المكتب (Desktop).\n- تم إنشاء اختصار في قائمة ابدأ (Start Menu).",
                    "Student Hub Setup",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );
            }
            catch (Exception ex)
            {
                MessageBox.Show("حدث خطأ أثناء التثبيت: " + ex.Message, "Student Hub Setup", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
    }
}
